import esbuild from "esbuild";
import { readFileSync } from "node:fs";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the repository of this plugin.
*/
`;

const mode = process.argv[2] ?? "dev";

if (mode === "verify") {
	await esbuild.build({
		entryPoints: ["scripts/verify.ts"],
		bundle: true,
		platform: "node",
		format: "cjs",
		outfile: "scripts/verify.cjs",
		logLevel: "info",
	});
	process.exit(0);
}

if (mode === "preview") {
	await esbuild.build({
		entryPoints: ["preview/main.ts"],
		bundle: true,
		platform: "browser",
		format: "iife",
		outfile: "preview/preview.js",
		logLevel: "info",
	});
	await esbuild.build({
		entryPoints: ["preview/embed-main.ts"],
		bundle: true,
		platform: "browser",
		format: "iife",
		outfile: "preview/embed.js",
		logLevel: "info",
	});
	process.exit(0);
}

const prod = mode === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	// esbuild's CJS wrapper exposes the default class as `.default`.
	// Obsidian expects `module.exports` to be the plugin class itself.
	// This file is not executed under Node (package.json is "type": "module");
	// Obsidian loads it as CommonJS from the vault plugin folder.
	footer: {
		js: "module.exports = module.exports.default;",
	},
});

if (prod) {
	await context.rebuild();
	const source = readFileSync("main.js", "utf8");
	if (!source.includes("module.exports = module.exports.default;")) {
		throw new Error("main.js is missing the Obsidian default-export footer");
	}
	if (/require\(["']electron["']\)/.test(source)) {
		throw new Error('main.js must not contain require("electron")');
	}
	const requires = [...source.matchAll(/require\(["']([^"']+)["']\)/g)].map((match) => match[1]);
	const foreign = requires.filter((id) => id !== "obsidian");
	if (foreign.length > 0) {
		throw new Error(`main.js may only require("obsidian"), found: ${foreign.join(", ")}`);
	}
	class Plugin {}
	class ItemView {}
	class PluginSettingTab {}
	class MarkdownRenderChild {}
	const obsidian = {
		Plugin,
		ItemView,
		PluginSettingTab,
		MarkdownRenderChild,
		Platform: { isDesktopApp: false },
		requestUrl() {
			return Promise.resolve({ status: 200, json: {} });
		},
		Setting: class Setting {},
	};
	const pluginModule = { exports: {} };
	const load = new Function("module", "exports", "require", source);
	load(pluginModule, pluginModule.exports, (id) => {
		if (id === "obsidian") return obsidian;
		throw new Error(`unexpected require(${id})`);
	});
	if (typeof pluginModule.exports !== "function") {
		throw new Error("main.js must export the plugin class");
	}
	if (!(pluginModule.exports.prototype instanceof Plugin)) {
		throw new Error("main.js export does not extend Plugin");
	}
	process.exit(0);
} else {
	await context.watch();
}
